import { ethers } from "ethers";

let contractAddress = null;
let contractABI = null;

// Load deployment info (generated by Hardhat deploy script)
export const loadContractInfo = async () => {
  try {
    const res = await fetch("/DisasterFund.json");
    const info = await res.json();
    contractAddress = info.address;
    contractABI = info.abi;
    return info;
  } catch {
    console.warn("Contract deployment info not found. Deploy first.");
    return null;
  }
};

export const getProvider = () => {
  if (!window.ethereum) throw new Error("MetaMask not installed");
  return new ethers.BrowserProvider(window.ethereum);
};

export const getSigner = async () => {
  const provider = getProvider();
  await provider.send("eth_requestAccounts", []);
  return provider.getSigner();
};

export const getContract = async (signerOrProvider) => {
  if (!contractABI) await loadContractInfo();
  return new ethers.Contract(contractAddress, contractABI, signerOrProvider);
};

// Connect MetaMask and return address
export const connectWallet = async () => {
  const signer = await getSigner();
  return signer.getAddress();
};

// Donate ETH to a disaster
export const donate = async (disasterId, amountEth) => {
  const signer = await getSigner();
  const contract = await getContract(signer);
  const tx = await contract.donate(disasterId, {
    value: ethers.parseEther(amountEth.toString()),
  });
  return tx.wait();
};

// Request disbursement (NGO)
export const requestDisbursement = async (recipientAddress, amountEth, disasterId) => {
  const signer = await getSigner();
  const contract = await getContract(signer);
  const tx = await contract.requestDisbursement(
    recipientAddress,
    ethers.parseEther(amountEth.toString()),
    disasterId
  );
  return tx.wait();
};

// Approve disbursement (Admin)
export const approveDisbursement = async (requestId) => {
  const signer = await getSigner();
  const contract = await getContract(signer);
  const tx = await contract.approveDisbursement(requestId);
  return tx.wait();
};

// Beneficiary withdrawal
export const withdraw = async () => {
  const signer = await getSigner();
  const contract = await getContract(signer);
  const tx = await contract.withdraw();
  return tx.wait();
};

const getReadProvider = () =>
  new ethers.JsonRpcProvider("http://127.0.0.1:8545");

// Read-only helpers
export const getContractBalance = async () => {
  const contract = await getContract(getReadProvider());
  const bal = await contract.getContractBalance();
  return ethers.formatEther(bal);
};

export const getAllocatedFunds = async (address) => {
  const contract = await getContract(getReadProvider());
  const bal = await contract.getAllocatedFunds(address);
  return ethers.formatEther(bal);
};

export const getTotalFunds = async () => {
  const contract = await getContract(getReadProvider());
  const bal = await contract.totalFunds();
  return ethers.formatEther(bal);
};
