import jsPDF from "jspdf";
import html2canvas from "html2canvas";

const esc = (v) => String(v ?? "").replace(/[&<>"']/g, (c) =>
  ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c])
);

function buildReceiptHTML(d) {
  const issued = new Date(d.timestamp || Date.now());
  const dateStr = issued.toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" });

  return `
    <div style="width: 720px; padding: 48px; background: #ffffff; color: #111827; font-family: 'Helvetica Neue', Arial, sans-serif; box-sizing: border-box;">
      <div style="display: flex; justify-content: space-between; align-items: flex-start; padding-bottom: 24px; border-bottom: 2px solid #4338ca;">
        <div>
          <div style="display: flex; align-items: center; gap: 10px; margin-bottom: 8px;">
            <div style="width: 32px; height: 32px; border-radius: 8px; background: linear-gradient(135deg, #7c3aed, #00d4ff); display: flex; align-items: center; justify-content: center; color: #fff; font-weight: 700; font-size: 16px;">⛓</div>
            <span style="font-size: 20px; font-weight: 800; letter-spacing: -0.5px; color: #111827;">SecureAidChain</span>
          </div>
          <p style="margin: 0; font-size: 11px; color: #6b7280; letter-spacing: 0.5px;">Blockchain-verified disaster relief</p>
        </div>
        <div style="text-align: right;">
          <p style="margin: 0; font-size: 10px; font-weight: 700; letter-spacing: 2px; text-transform: uppercase; color: #6b7280;">Donation Receipt</p>
          <p style="margin: 4px 0 0 0; font-size: 12px; color: #374151;">${esc(dateStr)}</p>
        </div>
      </div>

      <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 32px; margin-top: 32px;">
        <div>
          <p style="margin: 0 0 6px 0; font-size: 10px; font-weight: 700; letter-spacing: 1.5px; text-transform: uppercase; color: #6b7280;">Donor</p>
          <p style="margin: 0; font-size: 14px; font-weight: 600; color: #111827;">${esc(d.donorName || "Anonymous")}</p>
          ${d.donorEmail ? `<p style="margin: 2px 0 0 0; font-size: 12px; color: #4b5563;">${esc(d.donorEmail)}</p>` : ""}
          <p style="margin: 8px 0 0 0; font-size: 10px; font-family: 'Courier New', monospace; color: #6b7280; word-break: break-all;">${esc(d.donorWallet)}</p>
        </div>
        <div>
          <p style="margin: 0 0 6px 0; font-size: 10px; font-weight: 700; letter-spacing: 1.5px; text-transform: uppercase; color: #6b7280;">Campaign</p>
          <p style="margin: 0; font-size: 14px; font-weight: 600; color: #111827;">${esc(d.disasterTitle)}</p>
          <p style="margin: 2px 0 0 0; font-size: 12px; color: #4b5563;">${esc(d.disasterLocation || "")}</p>
          <p style="margin: 8px 0 0 0; font-size: 10px; font-family: 'Courier New', monospace; color: #6b7280;">${esc(d.disasterId)}</p>
        </div>
      </div>

      <div style="margin-top: 36px; padding: 28px; background: linear-gradient(135deg, #f5f3ff, #ecfeff); border-radius: 12px; border: 1px solid #e0e7ff; text-align: center;">
        <p style="margin: 0 0 8px 0; font-size: 10px; font-weight: 700; letter-spacing: 2px; text-transform: uppercase; color: #4338ca;">Amount Donated</p>
        <p style="margin: 0; font-size: 40px; font-weight: 800; letter-spacing: -1.5px; color: #4338ca; font-family: 'Courier New', monospace;">${esc(d.amount)} ETH</p>
      </div>

      <div style="margin-top: 36px;">
        <p style="margin: 0 0 12px 0; font-size: 10px; font-weight: 700; letter-spacing: 2px; text-transform: uppercase; color: #6b7280;">Blockchain Proof</p>
        <div style="display: grid; grid-template-columns: 140px 1fr; gap: 8px 16px; font-size: 11px;">
          <div style="color: #6b7280;">Transaction Hash</div>
          <div style="font-family: 'Courier New', monospace; color: #111827; word-break: break-all;">${esc(d.txHash)}</div>
          <div style="color: #6b7280;">Block Number</div>
          <div style="font-family: 'Courier New', monospace; color: #111827;">#${esc(d.blockNumber)}</div>
          <div style="color: #6b7280;">Network</div>
          <div style="color: #111827;">${esc(d.network || "Hardhat Local (Chain ID 31337)")}</div>
        </div>
      </div>

      <div style="margin-top: 32px; padding-top: 20px; border-top: 1px solid #e5e7eb;">
        <p style="margin: 0; font-size: 11px; color: #6b7280; line-height: 1.6;">
          This receipt is issued as proof of your donation to the campaign listed above. The transaction is recorded immutably on the Ethereum blockchain and can be independently verified using the transaction hash.
        </p>
        <p style="margin: 12px 0 0 0; font-size: 10px; color: #9ca3af; letter-spacing: 0.5px;">
          Generated by SecureAidChain · ${esc(issued.toISOString())}
        </p>
      </div>
    </div>
  `;
}

export async function downloadDonationReceipt(data) {
  const container = document.createElement("div");
  container.style.position = "fixed";
  container.style.left = "-10000px";
  container.style.top = "0";
  container.innerHTML = buildReceiptHTML(data);
  document.body.appendChild(container);

  try {
    const node = container.firstElementChild;
    const canvas = await html2canvas(node, { scale: 2, backgroundColor: "#ffffff", useCORS: true });
    const imgData = canvas.toDataURL("image/png");

    const pdf = new jsPDF({ orientation: "portrait", unit: "pt", format: "a4" });
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const imgWidth = pageWidth - 48;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    const y = imgHeight < pageHeight - 48 ? 24 : 24;
    pdf.addImage(imgData, "PNG", 24, y, imgWidth, imgHeight);

    const short = (data.txHash || "receipt").slice(2, 10);
    pdf.save(`SecureAidChain-receipt-${short}.pdf`);
  } finally {
    document.body.removeChild(container);
  }
}
